// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArMpIODVXJkVdXLv8wTzjMLGgS2rtdQvA',
    appId: '1:1040778134376:web:17c4b5abc5b07ce3ee8cdd',
    messagingSenderId: '1040778134376',
    projectId: 'fanzzi-a47d5',
    authDomain: 'fanzzi-a47d5.firebaseapp.com',
    storageBucket: 'fanzzi-a47d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVMxTyozwhT817vymyD3mVOTX-BlUjDRs',
    appId: '1:1040778134376:android:af353a08fc5c8452ee8cdd',
    messagingSenderId: '1040778134376',
    projectId: 'fanzzi-a47d5',
    storageBucket: 'fanzzi-a47d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbwB-c5r8-6T9MQZTP1xFHlaEhylV9YA',
    appId: '1:1040778134376:ios:a3bce41da4ccb5c2ee8cdd',
    messagingSenderId: '1040778134376',
    projectId: 'fanzzi-a47d5',
    storageBucket: 'fanzzi-a47d5.firebasestorage.app',
    iosBundleId: 'com.example.frontenduser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdbwB-c5r8-6T9MQZTP1xFHlaEhylV9YA',
    appId: '1:1040778134376:ios:a3bce41da4ccb5c2ee8cdd',
    messagingSenderId: '1040778134376',
    projectId: 'fanzzi-a47d5',
    storageBucket: 'fanzzi-a47d5.firebasestorage.app',
    iosBundleId: 'com.example.frontenduser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Li-urUWYD7gtky0o7_lkAnFv6eYNLqQ',
    appId: '1:1040778134376:web:3b41981255002fb2ee8cdd',
    messagingSenderId: '1040778134376',
    projectId: 'fanzzi-a47d5',
    authDomain: 'fanzzi-a47d5.firebaseapp.com',
    storageBucket: 'fanzzi-a47d5.firebasestorage.app',
  );
}
